services:
  - name: sk4film-backend
    type: web
    build:
      type: docker
      dockerfile: Dockerfile
      context: .
    ports:
      - port: 8000
        protocol: http
    regions:
      - fra
    instance_type: nano
    scaling:
      min: 1
      max: 1
    health_checks:
      - http:
          path: /
          port: 8000
        grace_period: 90
        interval: 30
        restart_limit: 3
    env:
      - PORT=8000
