services:
  - name: sk4film-complete
    type: web
    # REMOVED source_directory - files should be in root
    build:
      type: docker
      dockerfile: Dockerfile
    ports:
      - port: 8000
        protocol: http
    regions:
      - fra
    instance_type: nano
    scaling:
      min: 1
      max: 1
    env:
      - PORT=8000
